# src/planning/piano_geometry.py
import math
from dataclasses import dataclass

@dataclass
class KeyLocation:
    center_x: float  # meters, MuJoCo world X
    center_y: float  # meters, MuJoCo world Y (depth)
    center_z: float  # meters, MuJoCo world Z (height)
    is_black: bool

class PianoGeometry:
    """
    Piano geometry that is EXACTLY consistent with assets/piano.xml
    generated by scripts/generate_piano.py.
    
    - Same octave width and offsets
    - Same y/z placement (white vs black)
    - All units in METERS (MuJoCo convention)
    """

    def __init__(self, model=None):
        """
        Optional `model` arg is accepted for backwards compatibility with
        older code that called PianoGeometry(model). It is not required.
        """
        self.model = model

        # Must match scripts/generate_piano.py
        self.white_key_width_m = 0.0236
        self.octave_width_m = 0.164

        # is_white and offsets are indexed by "rel_note" from generate_piano.py:
        # rel_note = (midi - 21 + 9) % 12
        self.is_white_table = [
            True,  False, True,  False,
            True,  True,  False, True,
            False, True,  False, True
        ]
        self.offsets_m = [
            0.0,   0.014, 0.024, 0.041,
            0.048, 0.072, 0.083, 0.096,
            0.108, 0.120, 0.133, 0.144
        ]

        # Same global offset as generate_piano.py
        self.start_offset_m = -0.02

        # Y/Z placements copied from assets/piano.xml:
        #   White keys:  pos="{x} -0.1 0"
        #   Black keys:  pos="{x} -0.05 0.02"
        self.white_y_m = -0.1
        self.white_z_m = 0.0
        self.black_y_m = -0.05
        self.black_z_m = 0.02

    def _compute_x_from_midi(self, midi_pitch: int):
        """
        Reproduce the exact x-coordinate computation from scripts/generate_piano.py:
            rel_note = (midi - 21 + 9) % 12
            octave   = (midi - 21 + 9) // 12
            base_x   = octave * octave_width + offsets[rel_note] + start_offset

        Returns (x_position_m, is_white).
        """
        if midi_pitch < 21 or midi_pitch > 108:
            raise ValueError(f"MIDI pitch {midi_pitch} out of [21, 108] piano range.")

        rel_note = (midi_pitch - 21 + 9) % 12
        octave   = (midi_pitch - 21 + 9) // 12

        base_x = octave * self.octave_width_m + self.offsets_m[rel_note] + self.start_offset_m
        is_white = self.is_white_table[rel_note]
        return base_x, is_white

    def get_key_location(self, midi_pitch: int) -> KeyLocation:
        """
        Returns the key's geometric center as used in the MuJoCo XML (meters).
        This is the *body* position of the key, not the top surface of the cap,
        but it's a stable reference for lateral alignment.
        """
        center_x, is_white = self._compute_x_from_midi(midi_pitch)

        if is_white:
            center_y = self.white_y_m
            center_z = self.white_z_m
        else:
            center_y = self.black_y_m
            center_z = self.black_z_m
        
        is_black = not is_white

        return KeyLocation(center_x, center_y, center_z, is_black)
